### ISSUE TITLE
KeyError: 'state_dict'

### ISSUE THREAD

**Issue by sebastianopazo1** [tinyvision/SOLIDER-HumanParsing#2]
Hi! I was trying to use simple_extractor.py and got this error:
 python simple_extractor.py --input-dir /home/seba/Documents/SOLIDER/SOLIDER-HumanParsing/input --output-dir /home/seba/Documents/SOLIDER/SOLIDER-HumanParsing/output
Evaluating total class number 20 with ['Background', 'Hat', 'Hair', 'Glove', 'Sunglasses', 'Upper-clothes', 'Dress', 'Coat', 'Socks', 'Pants', 'Jumpsuits', 'Scarf', 'Skirt', 'Face', 'Left-arm', 'Right-arm', 'Left-leg', 'Right-leg', 'Left-shoe', 'Right-shoe']
Traceback (most recent call last):
  File "/home/seba/Documents/SOLIDER/SOLIDER-HumanParsing/simple_extractor.py", line 155, in <module>
    main()
  File "/home/seba/Documents/SOLIDER/SOLIDER-HumanParsing/simple_extractor.py", line 106, in main
    state_dict = torch.load(args.model_restore)['state_dict']
KeyError: 'state_dict'

Thanks!

**Comment by cedricnam** [comment]
> Hi! I was trying to use simple_extractor.py and got this error: python simple_extractor.py --input-dir /home/seba/Documents/SOLIDER/SOLIDER-HumanParsing/input --output-dir /home/seba/Documents/SOLIDER/SOLIDER-HumanParsing/output Evaluating total class number 20 with ['Background', 'Hat', 'Hair', 'Glove', 'Sunglasses', 'Upper-clothes', 'Dress', 'Coat', 'Socks', 'Pants', 'Jumpsuits', 'Scarf', 'Skirt', 'Face', 'Left-arm', 'Right-arm', 'Left-leg', 'Right-leg', 'Left-shoe', 'Right-shoe'] Traceback (most recent call last): File "/home/seba/Documents/SOLIDER/SOLIDER-HumanParsing/simple_extractor.py", line 155, in main() File "/home/seba/Documents/SOLIDER/SOLIDER-HumanParsing/simple_extractor.py", line 106, in main state_dict = torch.load(args.model_restore)['state_dict'] KeyError: 'state_dict'
> 
> Thanks!

I got same failed
